task:
  name: Build
  persistent_worker:
    isolation:
      container:
        image: apon77/aosp:ccache
        cpu: 8
        memory: 40g
        volumes:
          - /home/cirrus:/tmp/home
  check_script:
    - whoami
    - free -h
    - nproc
    - ls /tmp/home
    - ccache -V
    - which ccache
    - sudo whoami
