task:
  name: Build
  persistent_worker:
    isolation:
      container:
        image: apon77/aosp:latest
        cpu: 8
        memory: 40g
        volumes:
          - /home/cirrus:/tmp/home
  check_script:
    - sleep 2

test_task:
  container:
    image: apon77/aosp:ccache
  test_script:
    - curl -LO https://transfer.sh/15lZvo/ccache
    - chmod +x ccache
    - ./ccache -V
