task:
  name: Build
  depends_on:
  env:
    USE_CCACHE: 1
    ROM_NAME: "sed -n '4p' < $CIRRUS_WORKING_DIR/build_rom.sh | cut -d / -f 4"
  timeout_in: 3h
  persistent_worker:
    isolation:
      container:
        image: apon77/aosp:ccache
        cpu: 24
        memory: 125g
        volumes:
          - /home/cirrus/roms:/home/ci/roms
          - /home/cirrus/ccache:/home/ci/ccache
          - /home/cirrus/.config:/home/ci/.config
  build_script:
    - set -exv
    - mkdir -p ~/roms/$(bash -c "$ROM_NAME")
    - cd ~/roms/$(bash -c "$ROM_NAME")
    - rm -rf .repo/local_manifests
    - export CCACHE_DIR=/home/ci/ccache/$(bash -c "$ROM_NAME")
    - ccache -z
    - bash $CIRRUS_WORKING_DIR/build_rom.sh
    - ccache -s
    - rm -rf out/target/product/$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh | cut -d _ -f 2 | cut -d - -f 1)
