task:
  name: Build
  persistent_worker:
    isolation:
      container:
        image: apon77/aosp:latest
        cpu: 8
        memory: 40g
        volumes:
          - /home/cirrus:/tmp/home
  check_script:
    - tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a headless mode
    - tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
    - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
    - sleep 2h

test_task:
  container:
    image: apon77/aosp:ccache
  test_script:
    - set -exv
    - repo init --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x
    - repo sync vendor/aosp
