task:
  name: Build
  persistent_worker: {}
  env:
    USE_CCACHE: 1
    ROM_NAME: "grep init sync_rom.sh | cut -d / -f 4"
  sync_script:
    - mkdir -p /tmp/$(bash -c "$ROM_NAME") && cd "$_"
    - pwd
    - sleep 1m
    - bash $CIRRUS_WORKING_DIR/sync_rom.sh
  build_script:
    - bash $CIRRUS_WORKING_DIR/build_rom.sh
  upload_script:
    - bash $CIRRUS_WORKING_DIR/upload_rom.sh
  remove_script:
    - bash $CIRRUS_WORKING_DIR/upload_rom.sh
