test_task:
  container:
    image: apon77/aosp:ccache
  test_script:
    - ./ccache -V
    - which ccache
    - sleep 1
task:
  name: Build
  depends_on:
    - test
  persistent_worker:
    isolation:
      container:
        image: apon77/aosp:ccache
        cpu: 8
        memory: 40g
        volumes:
          - /home/cirrus/roms:/tmp/roms
          - /home/cirrus/.config/rclone:/home/ci/.config/rclone
  check_script:
    - ccache -V
    - rclone lsd cirrus:
    - sleep 2

